### ISSUE TITLE
RNFusedLocation error

### ISSUE THREAD

**Issue by wilsolutions** [BILDIT-Platform/react-native-bildit-flybuy#63]
**Describe the bug**
I updated the react-native-bildit-flybuy to the most recent stable release, version 2.1.3. Given that the current version 2.0.1 is functioning well, I anticipated that the update would also perform smoothly. However I got this error and I’m wondering if you guys have seen it before.

```
java.lang.RuntimeException: Could not invoke RNFusedLocation.getCurrentPosition
at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:383)
at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
at com.facebook.jni.NativeRunnable.run(Native Method)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Method.invoke(Native Method)
at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188) 
at com.facebook.jni.NativeRunnable.run(Native Method) 
at android.os.Handler.handleCallback(Handler.java:942) 
at android.os.Handler.dispatchMessage(Handler.java:99) 
at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27) 
at android.os.Looper.loopOnce(Looper.java:201) 
at android.os.Looper.loop(Looper.java:288) 
at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228) 
at java.lang.Thread.run(Thread.java:1012) 
Caused by: java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~xxx==/com.demoApp-yyyyy==/base.apk!classes8.dex)
at com.agontuk.RNFusedLocation.FusedLocationProvider.getCurrentLocation(FusedLocationProvider.java:97)
at com.agontuk.RNFusedLocation.RNFusedLocationModule.getCurrentPosition(RNFusedLocationModule.java:112)
```

**To Reproduce**
Launch the App and perform any geolocation call, eg: using: https://github.com/Agontuk/react-native-geolocation-service

**Expected behavior**
The react-native-bildit-flybuy works fine with react-native-geolocation-service

**Screenshots**
<img width="347" alt="Screenshot 2023-10-04 at 2 36 50 PM" src="https://github.com/BILDIT-Platform/react-native-bildit-flybuy/assets/474548/f339a29e-41b0-4826-ae68-ab4a1bcece36">

**Additional context**
Looks likes there is a conflict with the Geolocation, please note that the geolocation library works fine with Flybuy 2.0.1.

**Comment by wilsolutions** [comment]
Issue gone after bumping com.google.android.gms:play-services-location **from**:
`implementation "com.google.android.gms:play-services-location:20.0.0"`
**to**: 
`implementation "com.google.android.gms:play-services-location:21.0.0"`
