### ISSUE TITLE
Flybuy Core.Configure not getting called early enough

### ISSUE THREAD

**Issue by mohanenm** [BILDIT-Platform/react-native-bildit-flybuy#66]
**Describe the bug**

In certain cases, Core configure is not getting called which is causing crashes on android. Only Samsung devices running Android 10, 11, and 13 are impacted. 

**Stacktrace**

```
Fatal Exception: kotlin.UninitializedPropertyAccessException: lateinit property sites has not been initialized
       at com.radiusnetworks.flybuy.sdk.FlyBuyCore.getSites(:7)
       at com.reactnativeflybuy.FlybuyModule.fetchSiteByPartnerIdentifier(FlybuyModule.kt:571)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
       at java.lang.Thread.run(Thread.java:1012)

GmsDynamite:
       at java.lang.Object.wait(Object.java)
       at java.lang.Object.wait(Object.java:442)
       at java.lang.Object.wait(Object.java:568)
       at com.google.android.gms.dynamite.zza.run(com.google.android.gms:play-services-basement@@18.1.0:2)
```

**Additional context**
Code snippets and further details are in this issue: https://github.com/BILDIT-Platform/react-native-bildit-flybuy/issues/55

**Comment by mohanenm** [comment]
As a potential solution, we are trying to configure the Flybuy SDK on the native side to avoid crashes related to core not being configured, but we are running into the following issue:

In MainApplication.java:
```
import com.radiusnetworks.flybuy.sdk.FlyBuyCore;
import com.radiusnetworks.flybuy.sdk.pickup.PickupManager;
```
```
@Override
public void onCreate() {
  super.onCreate();
  SoLoader.init(this, /* native exopackage */ false);
  initializeFlipper(this, getReactNativeHost().getReactInstanceManager()); // Remove this line if you don't want Flipper enabled
  FlyBuyCore.configure(this, "123");
  PickupManager.getInstance().configure(this);
}
```
and getting the following error:
Cannot resolve method 'getInstance' in 'PickupManager'

**Comment by mohanenm** [comment]
cc: @botnerd @roshangm1

**Comment by addingama** [comment]
@mohanenm Is there any repository for minimum reproduction for this issue?

**Comment by mohanenm** [comment]
@addingama There is not, I have not been able to recreate it. However, the customer continuously faces the issue with their apps in production. 

Is moving the configuration calls to native code a viable option in this case? We think this would be the best way to make sure FlyBuy.core and PickupManager are called before any other flybuy methods are called.

**Comment by addingama** [comment]
@mohanenm I saw the official android documentation and noticed that the sample code is using Kotlin, but the android app is using Java

That's why you can't find the `getInstance` function there.

Please follow the changes in this PR https://github.com/BILDIT-Platform/react-native-bildit-flybuy/pull/67/files

**Comment by mohanenm** [comment]
Thank you @addingama
